#[repr(transparent)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub struct TpmCC(pub u32);

#[allow(non_upper_case_globals)]
impl TpmCC {
    pub const NV_UndefineSpaceSpecial: Self = Self(0x0000011F);
    pub const EvictControl: Self = Self(0x00000120);
    pub const HierarchyControl: Self = Self(0x00000121);
    pub const NV_UndefineSpace: Self = Self(0x00000122);
    pub const ChangeEPS: Self = Self(0x00000124);
    pub const ChangePPS: Self = Self(0x00000125);
    pub const Clear: Self = Self(0x00000126);
    pub const ClearControl: Self = Self(0x00000127);
    pub const ClockSet: Self = Self(0x00000128);
    pub const HierarchyChangeAuth: Self = Self(0x00000129);
    pub const NV_DefineSpace: Self = Self(0x0000012A);
    pub const PCR_Allocate: Self = Self(0x0000012B);
    pub const PCR_SetAuthPolicy: Self = Self(0x0000012C);
    pub const PP_Commands: Self = Self(0x0000012D);
    pub const SetPrimaryPolicy: Self = Self(0x0000012E);
    pub const FieldUpgradeStart: Self = Self(0x0000012F);
    pub const ClockRateAdjust: Self = Self(0x00000130);
    pub const CreatePrimary: Self = Self(0x00000131);
    pub const NV_GlobalWriteLock: Self = Self(0x00000132);
    pub const GetCommandAuditDigest: Self = Self(0x00000133);
    pub const NV_Increment: Self = Self(0x00000134);
    pub const NV_SetBits: Self = Self(0x00000135);
    pub const NV_Extend: Self = Self(0x00000136);
    pub const NV_Write: Self = Self(0x00000137);
    pub const NV_WriteLock: Self = Self(0x00000138);
    pub const DictionaryAttackLockReset: Self = Self(0x00000139);
    pub const DictionaryAttackParameters: Self = Self(0x0000013A);
    pub const NV_ChangeAuth: Self = Self(0x0000013B);
    pub const PCR_Event: Self = Self(0x0000013C);
    pub const PCR_Reset: Self = Self(0x0000013D);
    pub const SequenceComplete: Self = Self(0x0000013E);
    pub const SetAlgorithmSet: Self = Self(0x0000013F);
    pub const SetCommandCodeAuditStatus: Self = Self(0x00000140);
    pub const FieldUpgradeData: Self = Self(0x00000141);
    pub const IncrementalSelfTest: Self = Self(0x00000142);
    pub const SelfTest: Self = Self(0x00000143);
    pub const Startup: Self = Self(0x00000144);
    pub const Shutdown: Self = Self(0x00000145);
    pub const StirRandom: Self = Self(0x00000146);
    pub const ActivateCredential: Self = Self(0x00000147);
    pub const Certify: Self = Self(0x00000148);
    pub const PolicyNV: Self = Self(0x00000149);
    pub const CertifyCreation: Self = Self(0x0000014A);
    pub const Duplicate: Self = Self(0x0000014B);
    pub const GetTime: Self = Self(0x0000014C);
    pub const GetSessionAuditDigest: Self = Self(0x0000014D);
    pub const NV_Read: Self = Self(0x0000014E);
    pub const NV_ReadLock: Self = Self(0x0000014F);
    pub const ObjectChangeAuth: Self = Self(0x00000150);
    pub const PolicySecret: Self = Self(0x00000151);
    pub const Rewrap: Self = Self(0x00000152);
    pub const Create: Self = Self(0x00000153);
    pub const ECDH_ZGen: Self = Self(0x00000154);
    pub const HMAC: Self = Self(0x00000155);
    pub const Import: Self = Self(0x00000156);
    pub const Load: Self = Self(0x00000157);
    pub const Quote: Self = Self(0x00000158);
    pub const RSA_Decrypt: Self = Self(0x00000159);
    pub const HMAC_Start: Self = Self(0x0000015B);
    pub const SequenceUpdate: Self = Self(0x0000015C);
    pub const Sign: Self = Self(0x0000015D);
    pub const Unseal: Self = Self(0x0000015E);
    pub const PolicySigned: Self = Self(0x00000160);
    pub const ContextLoad: Self = Self(0x00000161);
    pub const ContextSave: Self = Self(0x00000162);
    pub const ECDH_KeyGen: Self = Self(0x00000163);
    pub const EncryptDecrypt: Self = Self(0x00000164);
    pub const FlushContext: Self = Self(0x00000165);
    pub const LoadExternal: Self = Self(0x00000167);
    pub const MakeCredential: Self = Self(0x00000168);
    pub const NV_ReadPublic: Self = Self(0x00000169);
    pub const PolicyAuthorize: Self = Self(0x0000016A);
    pub const PolicyAuthValue: Self = Self(0x0000016B);
    pub const PolicyCommandCode: Self = Self(0x0000016C);
    pub const PolicyCounterTimer: Self = Self(0x0000016D);
    pub const PolicyCpHash: Self = Self(0x0000016E);
    pub const PolicyLocality: Self = Self(0x0000016F);
    pub const PolicyNameHash: Self = Self(0x00000170);
    pub const PolicyOR: Self = Self(0x00000171);
    pub const PolicyTicket: Self = Self(0x00000172);
    pub const ReadPublic: Self = Self(0x00000173);
    pub const RSA_Encrypt: Self = Self(0x00000174);
    pub const StartAuthSession: Self = Self(0x00000176);
    pub const VerifySignature: Self = Self(0x00000177);
    pub const ECC_Parameters: Self = Self(0x00000178);
    pub const FirmwareRead: Self = Self(0x00000179);
    pub const GetCapability: Self = Self(0x0000017A);
    pub const GetRandom: Self = Self(0x0000017B);
    pub const GetTestResult: Self = Self(0x0000017C);
    pub const Hash: Self = Self(0x0000017D);
    pub const PCR_Read: Self = Self(0x0000017E);
    pub const PolicyPCR: Self = Self(0x0000017F);
    pub const PolicyRestart: Self = Self(0x00000180);
    pub const ReadClock: Self = Self(0x00000181);
    pub const PCR_Extend: Self = Self(0x00000182);
    pub const PCR_SetAuthValue: Self = Self(0x00000183);
    pub const NV_Certify: Self = Self(0x00000184);
    pub const EventSequenceComplete: Self = Self(0x00000185);
    pub const HashSequenceStart: Self = Self(0x00000186);
    pub const PolicyPhysicalPresence: Self = Self(0x00000187);
    pub const PolicyDuplicationSelect: Self = Self(0x00000188);
    pub const PolicyGetDigest: Self = Self(0x00000189);
    pub const TestParms: Self = Self(0x0000018A);
    pub const Commit: Self = Self(0x0000018B);
    pub const PolicyPassword: Self = Self(0x0000018C);
    pub const ZGen_2Phase: Self = Self(0x0000018D);
    pub const EC_Ephemeral: Self = Self(0x0000018E);
    pub const PolicyNvWritten: Self = Self(0x0000018F);
    pub const PolicyTemplate: Self = Self(0x00000190);
    pub const CreateLoaded: Self = Self(0x00000191);
    pub const PolicyAuthorizeNV: Self = Self(0x00000192);
    pub const EncryptDecrypt2: Self = Self(0x00000193);
    pub const AC_GetCapability: Self = Self(0x00000194);
    pub const AC_Send: Self = Self(0x00000195);
    pub const Policy_AC_SendSelect: Self = Self(0x00000196);
    pub const CertifyX509: Self = Self(0x00000197);
    pub const ACT_SetTimeout: Self = Self(0x00000198);
    pub const ECC_Encrypt: Self = Self(0x00000199);
    pub const ECC_Decrypt: Self = Self(0x0000019A);
    pub const PolicyCapability: Self = Self(0x0000019B);
    pub const PolicyParameters: Self = Self(0x0000019C);
    pub const NV_DefineSpace2: Self = Self(0x0000019D);
    pub const NV_ReadPublic2: Self = Self(0x0000019E);
    pub const SetCapability: Self = Self(0x0000019F);
    pub const ReadOnlyControl: Self = Self(0x000001A0);
    pub const PolicyTransportSPDM: Self = Self(0x000001A1);
}

impl TpmCC {
    pub fn as_str(self) -> &'static str {
        match self {
            TpmCC::NV_UndefineSpaceSpecial => "NV_UndefineSpaceSpecial",
            TpmCC::EvictControl => "EvictControl",
            TpmCC::HierarchyControl => "HierarchyControl",
            TpmCC::NV_UndefineSpace => "NV_UndefineSpace",
            TpmCC::ChangeEPS => "ChangeEPS",
            TpmCC::ChangePPS => "ChangePPS",
            TpmCC::Clear => "Clear",
            TpmCC::ClearControl => "ClearControl",
            TpmCC::ClockSet => "ClockSet",
            TpmCC::HierarchyChangeAuth => "HierarchyChangeAuth",
            TpmCC::NV_DefineSpace => "NV_DefineSpace",
            TpmCC::PCR_Allocate => "PCR_Allocate",
            TpmCC::PCR_SetAuthPolicy => "PCR_SetAuthPolicy",
            TpmCC::PP_Commands => "PP_Commands",
            TpmCC::SetPrimaryPolicy => "SetPrimaryPolicy",
            TpmCC::FieldUpgradeStart => "FieldUpgradeStart",
            TpmCC::ClockRateAdjust => "ClockRateAdjust",
            TpmCC::CreatePrimary => "CreatePrimary",
            TpmCC::NV_GlobalWriteLock => "NV_GlobalWriteLock",
            TpmCC::GetCommandAuditDigest => "GetCommandAuditDigest",
            TpmCC::NV_Increment => "NV_Increment",
            TpmCC::NV_SetBits => "NV_SetBits",
            TpmCC::NV_Extend => "NV_Extend",
            TpmCC::NV_Write => "NV_Write",
            TpmCC::NV_WriteLock => "NV_WriteLock",
            TpmCC::DictionaryAttackLockReset => "DictionaryAttackLockReset",
            TpmCC::DictionaryAttackParameters => "DictionaryAttackParameters",
            TpmCC::NV_ChangeAuth => "NV_ChangeAuth",
            TpmCC::PCR_Event => "PCR_Event",
            TpmCC::PCR_Reset => "PCR_Reset",
            TpmCC::SequenceComplete => "SequenceComplete",
            TpmCC::SetAlgorithmSet => "SetAlgorithmSet",
            TpmCC::SetCommandCodeAuditStatus => "SetCommandCodeAuditStatus",
            TpmCC::FieldUpgradeData => "FieldUpgradeData",
            TpmCC::IncrementalSelfTest => "IncrementalSelfTest",
            TpmCC::SelfTest => "SelfTest",
            TpmCC::Startup => "Startup",
            TpmCC::Shutdown => "Shutdown",
            TpmCC::StirRandom => "StirRandom",
            TpmCC::ActivateCredential => "ActivateCredential",
            TpmCC::Certify => "Certify",
            TpmCC::PolicyNV => "PolicyNV",
            TpmCC::CertifyCreation => "CertifyCreation",
            TpmCC::Duplicate => "Duplicate",
            TpmCC::GetTime => "GetTime",
            TpmCC::GetSessionAuditDigest => "GetSessionAuditDigest",
            TpmCC::NV_Read => "NV_Read",
            TpmCC::NV_ReadLock => "NV_ReadLock",
            TpmCC::ObjectChangeAuth => "ObjectChangeAuth",
            TpmCC::PolicySecret => "PolicySecret",
            TpmCC::Rewrap => "Rewrap",
            TpmCC::Create => "Create",
            TpmCC::ECDH_ZGen => "ECDH_ZGen",
            TpmCC::HMAC => "HMAC",
            TpmCC::Import => "Import",
            TpmCC::Load => "Load",
            TpmCC::Quote => "Quote",
            TpmCC::RSA_Decrypt => "RSA_Decrypt",
            TpmCC::HMAC_Start => "HMAC_Start",
            TpmCC::SequenceUpdate => "SequenceUpdate",
            TpmCC::Sign => "Sign",
            TpmCC::Unseal => "Unseal",
            TpmCC::PolicySigned => "PolicySigned",
            TpmCC::ContextLoad => "ContextLoad",
            TpmCC::ContextSave => "ContextSave",
            TpmCC::ECDH_KeyGen => "ECDH_KeyGen",
            TpmCC::EncryptDecrypt => "EncryptDecrypt",
            TpmCC::FlushContext => "FlushContext",
            TpmCC::LoadExternal => "LoadExternal",
            TpmCC::MakeCredential => "MakeCredential",
            TpmCC::NV_ReadPublic => "NV_ReadPublic",
            TpmCC::PolicyAuthorize => "PolicyAuthorize",
            TpmCC::PolicyAuthValue => "PolicyAuthValue",
            TpmCC::PolicyCommandCode => "PolicyCommandCode",
            TpmCC::PolicyCounterTimer => "PolicyCounterTimer",
            TpmCC::PolicyCpHash => "PolicyCpHash",
            TpmCC::PolicyLocality => "PolicyLocality",
            TpmCC::PolicyNameHash => "PolicyNameHash",
            TpmCC::PolicyOR => "PolicyOR",
            TpmCC::PolicyTicket => "PolicyTicket",
            TpmCC::ReadPublic => "ReadPublic",
            TpmCC::RSA_Encrypt => "RSA_Encrypt",
            TpmCC::StartAuthSession => "StartAuthSession",
            TpmCC::VerifySignature => "VerifySignature",
            TpmCC::ECC_Parameters => "ECC_Parameters",
            TpmCC::FirmwareRead => "FirmwareRead",
            TpmCC::GetCapability => "GetCapability",
            TpmCC::GetRandom => "GetRandom",
            TpmCC::GetTestResult => "GetTestResult",
            TpmCC::Hash => "Hash",
            TpmCC::PCR_Read => "PCR_Read",
            TpmCC::PolicyPCR => "PolicyPCR",
            TpmCC::PolicyRestart => "PolicyRestart",
            TpmCC::ReadClock => "ReadClock",
            TpmCC::PCR_Extend => "PCR_Extend",
            TpmCC::PCR_SetAuthValue => "PCR_SetAuthValue",
            TpmCC::NV_Certify => "NV_Certify",
            TpmCC::EventSequenceComplete => "EventSequenceComplete",
            TpmCC::HashSequenceStart => "HashSequenceStart",
            TpmCC::PolicyPhysicalPresence => "PolicyPhysicalPresence",
            TpmCC::PolicyDuplicationSelect => "PolicyDuplicationSelect",
            TpmCC::PolicyGetDigest => "PolicyGetDigest",
            TpmCC::TestParms => "TestParms",
            TpmCC::Commit => "Commit",
            TpmCC::PolicyPassword => "PolicyPassword",
            TpmCC::ZGen_2Phase => "ZGen_2Phase",
            TpmCC::EC_Ephemeral => "EC_Ephemeral",
            TpmCC::PolicyNvWritten => "PolicyNvWritten",
            TpmCC::PolicyTemplate => "PolicyTemplate",
            TpmCC::CreateLoaded => "CreateLoaded",
            TpmCC::PolicyAuthorizeNV => "PolicyAuthorizeNV",
            TpmCC::EncryptDecrypt2 => "EncryptDecrypt2",
            TpmCC::AC_GetCapability => "AC_GetCapability",
            TpmCC::AC_Send => "AC_Send",
            TpmCC::Policy_AC_SendSelect => "Policy_AC_SendSelect",
            TpmCC::CertifyX509 => "CertifyX509",
            TpmCC::ACT_SetTimeout => "ACT_SetTimeout",
            TpmCC::ECC_Encrypt => "ECC_Encrypt",
            TpmCC::ECC_Decrypt => "ECC_Decrypt",
            TpmCC::PolicyCapability => "PolicyCapability",
            TpmCC::PolicyParameters => "PolicyParameters",
            TpmCC::NV_DefineSpace2 => "NV_DefineSpace2",
            TpmCC::NV_ReadPublic2 => "NV_ReadPublic2",
            TpmCC::SetCapability => "SetCapability",
            TpmCC::ReadOnlyControl => "ReadOnlyControl",
            TpmCC::PolicyTransportSPDM => "PolicyTransportSPDM",
            _ => "Unknown",
        }
    }
}
