# Copyright 2025 The Pigweed Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

load("@rules_rust//rust:defs.bzl", "rust_library")
load("//target/earlgrey:defs.bzl", "TARGET_COMPATIBLE_WITH")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "server",
    srcs = [
        "lib.rs",
        "digest.rs",
        "asymmetric.rs",
        "server.rs",
    ],
    crate_name = "crypto_server",
    edition = "2024",
    target_compatible_with = TARGET_COMPATIBLE_WITH,
    deps = [
        "//util/misc",
        "//crypto/common",
        "//target/earlgrey/cryptolib:otcrypto",
        "@pigweed//pw_kernel/syscall:syscall_user",
        "@pigweed//pw_kernel/userspace",
        "@pigweed//pw_status/rust:pw_status",
        "@pigweed//pw_log/rust:pw_log",
        "@rust_crates//:zerocopy",
    ],
    proc_macro_deps = [
        "@rust_crates//:paste",
    ],
)
